[database]
connection-type="mysql"
user-name="root"
password="12345678"
host="mysql:3306"
database-name="oj"
charset="utf8mb4"
parse-time=true
location="Local"

[redis]
connection-type="tcp"
host="redis:6379"
password=""
database=0
max-idle=100
max-active=100
connection-timeout="1s"
write-timeout="1s"
read-timeout="1s"
idle-timeout="1s"
wait=true

[sphinx-core]
cluster-host=["10.105.242.94:9092"]

[path]
problem-path="./problem/"
code-path="./submission/"