package main

import (
	"encoding/json"
	"github.com/Myriad-Dreamin/artisan/artisan-core"
	"github.com/Myriad-Dreamin/artisan/extension/artisan-swagger"
	"github.com/Myriad-Dreamin/boj-v6/types"
	"github.com/Myriad-Dreamin/minimum-lib/sugar"
	"github.com/go-openapi/spec"
	"io/ioutil"
)

var codeField = artisan_core.Param("code", new(types.ServiceCode))
var required = artisan_core.Tag("binding", "required")
var routeParam = artisan_core.Tag("route-param", "-")

type Meta struct {
	artisan_core.RouterMeta
}

func (m *Meta) NeedAuth() *Meta {
	return &Meta{
		RouterMeta: artisan_core.RouterMeta{
			RuntimeRouterMeta: m.RuntimeRouterMeta,
			NeedAuth:          true,
		},
	}
}

//func controllerMethods(controller artisan_core.ServiceDescription) (res string) {
//	res = fmt.Sprintf("    %sSignatureXXX() interface{}\n", controller.GetName())
//	for _, cat := range controller.GetCategories() {
//		res += _controllerMethods(cat)
//	}
//	return
//}

//func _controllerMethods(controller artisan_core.CategoryDescription) (res string) {
//	for _, cat := range controller.GetCategories() {
//		res += _controllerMethods(cat)
//	}
//	for _, method := range controller.GetMethods() {
//		res += "    " + method.GetName() + "(c controller.MContext, req *api." + method.GetName() + "Request) (*api." + method.GetName() + "Reply, error) \n"
//	}
//	return
//}

func main() {
	v1 := "/v1"

	//instantiate
	var meta = []struct {
		cate artisan_core.ProposingService
		name string
	}{
		{DescribeUserController(), "user"},
		{DescribeAuthController(), "auth"},
		{DescribeAnnouncementController(), "announcement"},
		{DescribeCommentController(), "comment"},
		{DescribeSubmissionController(), "submission"},
		{DescribeProblemController(), "problem"},
		{DescribeContestController(), "contest"},
		{DescribeGroupController(), "group"},
	}

	var controller *artisan_core.PublishedServices
	var controllers []artisan_core.ProposingService
	for _, tsk := range meta {
		controllers = append(controllers, tsk.cate)
	}
	controller = artisan_core.NewService(controllers...).HumanInfo(&spec.Swagger{
		SwaggerProps: spec.SwaggerProps{
			Info: &spec.Info{
				InfoProps: spec.InfoProps{
					Title:       "BOJ-v6 Backend",
					Description: "Generated by artisan-swagger. GitHub Repo: https://github.com/Myriad-Dreamin/boj-v6",
					Version:     "v0.5.0",
				},
			},
		},
	}).Base(v1).SetPackageName("api").Final()

	sugar.HandlerError0(controller.PublishRouter("api/router.go"))
	b, err := json.Marshal(artisan_swagger.GenerateSwagger(controller))
	sugar.HandlerError0(err)
	//var conv map[string]interface{}
	//err = json.Unmarshal(b, &conv)
	//sugar.HandlerError0(err)
	//b, err = yaml.Marshal(conv)
	//sugar.HandlerError0(err)

	sugar.HandlerError0(ioutil.WriteFile("doc/main_spec.json", b, 0644))

	for _, tsk := range meta {
		subController := controller.GetService(tsk.cate)
		delete(controller.GetServices(), tsk.cate)

		sugar.HandlerError0(controller.PublishObjects(
			subController.SetFilePath("api/" + tsk.name + ".go")))
		sugar.HandlerError0(subController.SetFilePath(
			"abstract/control/"+tsk.name+"-interface.go").PublishInterface(
			"control", controller.Opts))

		//		sugar.HandlerError0(ioutil.WriteFile(
		//			"abstract/inner-control/"+tsk.name+"-inner-interface.go",
		//			[]byte(fmt.Sprintf(`
		//package inner_control
		//
		//import (
		//	"github.com/Myriad-Dreamin/boj-v6/api"
		//    "github.com/Myriad-Dreamin/minimum-lib/controller"
		//)
		//
		//type Inner%s interface {
		//%s}`, subController.GetName(), controllerMethods(subController))), 0644))
	}

	sugar.HandlerError0(controller.Publish())
}
